# Generated by Django 5.0.2 on 2024-03-18 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0006_alter_postdetails_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postdetails',
            name='image',
            field=models.CharField(max_length=10000),
        ),
    ]
