# Generated by Django 5.0.2 on 2024-04-26 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0011_contactdetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactdetails',
            name='contactno',
            field=models.BigIntegerField(),
        ),
    ]
